In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('Dataset/Employees.csv')
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [4]:
'''
Filter data on basis of certain required conditions.
'''

'\nFilter data on basis of certain required conditions.\n'

In [7]:
# Find details of employees whose salary is in range of 5000 to 8000.
# Find details of employees whose salary is more than 5000 and less than 8000.
emp_sal = (df['SALARY'] >= 5000) & (df['SALARY'] <= 8000)
# df[emp_sal]
df.loc[emp_sal, ['FIRST_NAME', 'LAST_NAME', 'SALARY']]

      FIRST_NAME  LAST_NAME  SALARY
4          Bruce      Ernst    6000
11        Ismael    Sciarra    7700
12   Jose Manuel      Urman    7800
13          Luis       Popp    6900
20       Matthew      Weiss    8000
22         Payam   Kaufling    7900
23        Shanta    Vollman    6500
24         Kevin    Mourgos    5800
53   Christopher      Olsen    8000
54       Nanette  Cambrault    7500
55        Oliver    Tuvault    7000
59       Lindsey      Smith    8000
60        Louise      Doran    7500
61        Sarath     Sewall    7000
64        Mattea    Marvins    7200
65         David        Lee    6800
66        Sundar       Ande    6400
67          Amit      Banda    6200
71       William      Smith    7400
72     Elizabeth      Bates    7300
73       Sundita      Kumar    6100
78     Kimberely      Grant    7000
79       Charles    Johnson    6200
102          Pat        Fay    6000
103        Susan     Mavris    6500
107        Susan     Mavris    6500

In [6]:
# Between

In [8]:
sal_between = df['SALARY'].between(5000, 8000)
df[sal_between]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
11,111,Ismael,Sciarra,ISCIARRA,515.124.4369,9/30/2005,FI_ACCOUNT,7700,NaN,108.0,100.0
12,112,Jose Manuel,Urman,JMURMAN,515.124.4469,3/7/2006,FI_ACCOUNT,7800,NaN,108.0,100.0
13,113,Luis,Popp,LPOPP,515.124.4567,12/7/2007,FI_ACCOUNT,6900,NaN,108.0,100.0
20,120,Matthew,Weiss,MWEISS,650.123.1234,7/18/2004,ST_MAN,8000,NaN,100.0,50.0
22,122,Payam,Kaufling,PKAUFLIN,650.123.3234,5/1/2003,ST_MAN,7900,NaN,100.0,50.0
23,123,Shanta,Vollman,SVOLLMAN,650.123.4234,10/10/2005,ST_MAN,6500,NaN,100.0,50.0
24,124,Kevin,Mourgos,KMOURGOS,650.123.5234,11/16/2007,ST_MAN,5800,NaN,100.0,50.0
53,153,Christopher,Olsen,COLSEN,011.44.1344.498718,3/30/2006,SA_REP,8000,0.20,145.0,80.0
54,154,Nanette,Cambrault,NCAMBRAU,011.44.1344.987668,12/9/2006,SA_REP,7500,0.20,145.0,80.0
55,155,Oliver,Tuvault,OTUVAULT,011.44.1344.486508,11/23/2007,SA_REP,7000,0.15,145.0,80.0
59,159,Lindsey,Smith,LSMITH,011.44.1345.729268,3/10/2005,SA_REP,8000,0.30,146.0,80.0
60,160,Louise,Doran,LDORAN,011.44.1345.629268,12/15/2005,SA_REP,7500,0.30,146.0,80.0
61,161,Sarath,Sewall,SSEWALL,011.44.1345.529268,11/3/2006,SA_REP,7000,0.25,146.0,80.0
64,164,Mattea,Marvins,MMARVINS,011.44.1346.329268,1/24/2008,SA_REP,7200,0.10,147.0,80.0
65,165,David,Lee,DLEE,011.44.1346.529268,2/23/2008,SA_REP,6800,0.10,147.0,80.0
66,166,Sundar,Ande,SANDE,011.44.1346.629268,3/24/2008,SA_REP,6400,0.10,147.0,80.0
67,167,Amit,Banda,ABANDA,011.44.1346.729268,4/21/2008,SA_REP,6200,0.10,147.0,80.0
71,171,William,Smith,WSMITH,011.44.1343.629268,2/23/2007,SA_REP,7400,0.15,148.0,80.0
72,172,Elizabeth,Bates,EBATES,011.44.1343.529268,3/24/2007,SA_REP,7300,0.15,148.0,80.0
73,173,Sundita,Kumar,SKUMAR,011.44.1343.329268,4/21/2008,SA_REP,6100,0.10,148.0,80.0
78,178,Kimberely,Grant,KGRANT,011.44.1644.429263,5/24/2007,SA_REP,7000,0.15,149.0,NaN
79,179,Charles,Johnson,CJOHNSON,011.44.1644.429262,1/4/2008,SA_REP,6200,0.10,149.0,80.0
102,202,Pat,Fay,PFAY,603.123.6666,8/17/2005,MK_REP,6000,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0

In [11]:
'''
Find details of employees whose salary is in range of 5000 to 8000 
and who must work in HR_REP Job.
'''
emp_sal_job = ((df['SALARY'] >= 5000) & (df['SALARY'] <= 8000)) & (df['JOB_ID'] == 'HR_REP')
df[emp_sal_job]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
103,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0

In [16]:
sal = emp_sal = (df['SALARY'] >= 5000) & (df['SALARY'] <= 8000)
df_sal = df[sal]
sal_job = df_sal['JOB_ID'] == 'HR_REP'

In [18]:
df_sal[sal_job]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
103,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0

In [19]:
# Find employees who works under department 60 and 90.
emp_dep = (df['DEPARTMENT_ID'] == 60) | (df['DEPARTMENT_ID'] == 90)
df[emp_dep]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,6/25/2005,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,2/5/2006,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,2/7/2007,IT_PROG,4200,NaN,103.0,60.0

In [21]:
'''
Find employees who works under department 60 and 90 and their salary
must be in range of 6000 to 10000.
'''
emp_in = (df['DEPARTMENT_ID'].isin([60, 90])) & (df['SALARY'].between(6000, 10000))
df[emp_in]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0

In [ ]:
'''
1. Data Cleaning
2. Feature Engineering
3. Data Analysis -> Python Pandas & SQL
4. Data Visualization -> Python Vis / Tableau
5. Machine Learning / NLP / AI
'''