In [1]:
'''
Pandas
------------
Used for Conditinal Filtering, Data Cleaning, Feature Engineering, Data Analysis,
File read and write

Data Cleaning, Feature Engineering -> Data Wrangling
'''

'\nPandas\n------------\nUsed for Conditinal Filtering, Data Cleaning, Feature Engineering, Data Analysis,\nFile read and write\n\nData Cleaning, Feature Engineering -> Data Wrangling\n'

In [2]:
# 1D -> Series
# 2D/Multi-D -> DataFrame

In [1]:
import pandas as pd

In [10]:
numbers = pd.Series([1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])
numbers

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [6]:
num = [1, 2, 3, 4, 5]
# enumerate -> return both index and value of list
for idx, val in enumerate(num):
    print(f'{idx}: {val}')

0: 1
1: 2
2: 3
3: 4
4: 5

In [13]:
personal_details = pd.DataFrame([
    ["Ram", 30, "Lalitpur", "Bachelors"],
    ["Shaym", 35, "Kathmandu", "Masters"],
    ["Hari", 40, "Bhaktapur", "PhD"],
    ["Gopal", 15, "Jhapa", "School"],
    ["Sita", 25, "Banke", "Bachelors"],
    ["Gita", 20, "Palpa", "Bachelors"],
    ["Rita", 30, "Mahendranagar", "Masters"]
], columns=['Name', 'Age', 'Address', 'Qualifications'], index=['A', 'B', 'C', 'D', 'E', 'F', 'G'])
personal_details

    Name  Age        Address Qualifications
A    Ram   30       Lalitpur      Bachelors
B  Shaym   35      Kathmandu        Masters
C   Hari   40      Bhaktapur            PhD
D  Gopal   15          Jhapa         School
E   Sita   25          Banke      Bachelors
F   Gita   20          Palpa      Bachelors
G   Rita   30  Mahendranagar        Masters

In [20]:
numbers['A':'C']

A    1
B    2
C    3
dtype: int64

# loc and iloc

In [ ]:
'''
Loc -> Location -> (Used for Alphabetical Indexing)
iloc -> Integer Location -> (Used for Numerical Indexing)
'''

In [25]:
# dataframe_name[row, column]
personal_details.iloc[0:3, 0:3]

    Name  Age    Address
A    Ram   30   Lalitpur
B  Shaym   35  Kathmandu
C   Hari   40  Bhaktapur

In [27]:
personal_details.loc['A':'C', 'Name':'Address']

    Name  Age    Address
A    Ram   30   Lalitpur
B  Shaym   35  Kathmandu
C   Hari   40  Bhaktapur

In [28]:
personal_details.iloc[
    [1, 4],
    [1, 2]
]

   Age    Address
B   35  Kathmandu
E   25      Banke

In [32]:
personal_details.loc[
    ['A']
]

  Name  Age   Address Qualifications
A  Ram   30  Lalitpur      Bachelors

In [16]:
# # Slicing to extract specific details
# personal_details.iloc[
#     [1, 4],
#     [1, 3]
# ]

In [17]:
# personal_details.loc[
#     ['B', 'E'],
#     ['Age', 'Qualification']
# ]

# Basic functions for working with data

In [17]:
# info() -> Used to get full information about data
personal_details.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, A to G
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           7 non-null      object
 1   Age            7 non-null      int64
 2   Address        7 non-null      object
 3   Qualification  7 non-null      object
dtypes: int64(1), object(3)
memory usage: 580.0+ bytes

In [20]:
# Used to show all column names of dataset
personal_details.columns

Index(['Name', 'Age', 'Address', 'Qualification'], dtype='object')

In [21]:
# Unique() -> Extract all unique records of a column
personal_details['Qualification'].unique()

array(['Bachelors', 'Masters', 'PhD', 'School'], dtype=object)

# Read Data File

In [22]:
# Read Excel File
# read_excel()
emp_xlxs = pd.read_excel('Dataset/EMPLOYEES.xlsx')
emp_xlxs

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,17.06.2003 00:00:00,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,21.09.2005 00:00:00,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,13.01.2001 00:00:00,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,03.01.2006 00:00:00,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,21.05.2007 00:00:00,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,07.06.2002 00:00:00,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,07.06.2002 00:00:00,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,07.06.2002 00:00:00,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,07.06.2002 00:00:00,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,07.06.2002 00:00:00,AC_ACCOUNT,8300,NaN,205.0,110.0

In [33]:
# Read CSV File
# read_csv()
emp_csv = pd.read_csv('Dataset/Employees.csv')
emp_csv

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [36]:
# extract top 5
emp_csv.head(10)

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,6/25/2005,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,2/5/2006,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,2/7/2007,IT_PROG,4200,NaN,103.0,60.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,8/17/2002,FI_MGR,12008,NaN,101.0,100.0
9,109,Daniel,Faviet,DFAVIET,515.124.4169,8/16/2002,FI_ACCOUNT,9000,NaN,108.0,100.0

In [35]:
# extract bottom 5
emp_csv.tail()

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [ ]:
'''
NaN -> Not a Number
NaT -> Not a Time
'''

In [27]:
emp_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EMPLOYEE_ID     111 non-null    int64
 1   FIRST_NAME      111 non-null    object
 2   LAST_NAME       111 non-null    object
 3   EMAIL           111 non-null    object
 4   PHONE_NUMBER    111 non-null    object
 5   HIRE_DATE       111 non-null    object
 6   JOB_ID          111 non-null    object
 7   SALARY          111 non-null    int64
 8   COMMISSION_PCT  35 non-null     float64
 9   MANAGER_ID      110 non-null    float64
 10  DEPARTMENT_ID   110 non-null    float64
dtypes: float64(3), int64(2), object(6)
memory usage: 9.7+ KB